### ISSUE TITLE
Margin issue in title

### ISSUE THREAD

**Issue by uditjainstjis** [Rishabh32700/ytClone#13]
<img width="677" alt="image" src="https://github.com/user-attachments/assets/520728c6-764d-4271-807c-81266f5caef3">
when playing video, other video's are visible on right hand side, but the title gap between title and thumbnail of those videos is very high, making website look cheap.

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well
I would like to work on this issue

Thanks and Regards,
Mohit Kambli
